### ISSUE TITLE
Nice to haves

### ISSUE THREAD

**Issue by heypaxton** [LegenChandler/CMDSense#1]
- [x] User on-boarding (touch here to begin, walk in measuring direction, etc..)
- [x] Display of distance between points on line, example X1 (0' 0"), X2 (10' 2" from X1) 
- [x] App icon (can supply)

**Comment by heypaxton** [comment]
@LegenChandler the app icons are attached
[icons.zip](https://github.com/LegenChandler/CMDSense/files/1619604/icons.zip)

**Comment by LegenChandler** [comment]
Done!
